version: '3.0'
services:
  streetmerchant:
    image: ghcr.io/jef/streetmerchant:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant
    env_file:
      - dotenv
