version: "3.8"

services:
  streetmerchant:
    image: ghcr.io/jef/streetmerchant:nightly
    env_file: .env
    stdin_open: true
    tty: true
    init: true
    container_name: playstation
    cap_add:
      - SYS_ADMIN
    restart: always
