apiVersion: apps/v1
kind: Deployment
metadata:
  name: streetmerchant
  namespace: dev
  labels:
    app: streetmerchant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streetmerchant
  template:
    metadata:
      labels:
        app: streetmerchant
    spec:
      containers:
        - name: streetmerchant
          image: registry.knstyl.com/streetmerchant:latest
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: streetmerchant-dotenv
          - secretRef:
              name: streetmerchant-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2022-02-18T18:52:05Z
  name: streetmerchant-dotenv
  namespace: dev
data:
  MICROCENTER_LOCATION: web, brooklyn, westbury, yonkers, flushing, rockville, north-jersey
  SHOW_ONLY_BRANDS: asrock, asus
  SHOW_ONLY_MODELS: nova, tuf, strix
  SHOW_ONLY_SERIES: x870e, 4080-16g, 4080-super
  STORES: amazon, bestbuy, newegg, microcenter
