apiVersion: apps/v1
kind: Deployment
metadata:
  name: streetmerchant
  namespace: dev
  labels:
    app: streetmerchant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streetmerchant
  template:
    metadata:
      labels:
        app: streetmerchant
    spec:
      containers:
        - name: streetmerchant
          image: registry.dev.svc.cluster.local:5000/streetmerchant:latest
          ports:
            - containerPort: 8080