import {Store} from './store';

export const Globaldata: Store = {
  currency: '€',
  labels: {
    inStock: {
      container:
        'body > main > div.main-container > div.container.mb-5 > div.row.align-items-lg-start.z-above-pattern > ck-product-cta-box > div > div.d-flex.mt-4 > div.w-100 > ck-addto-cart-wrapper > form > div > div.w-100.pl-3 > button > span',
      text: ['Adicionar ao carrinho'],
    },
    outOfStock: {
      container:
        'body > main > div.main-container > div.container.mb-5 > div.row.align-items-lg-start.z-above-pattern > ck-product-cta-box > div > div.d-flex.mt-4 > div.w-100 > button',
      text: ['Notifique-me quando estiver em stock'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.globaldata.pt/drive-externa-dvdr-asus-sdrw-08d2s-u-lite-8x-branco-usb-20-90-dq0436-ua221kz',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3070-gaming-oc-8gb-gd6-gv-n3070gam-oc-8g',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3080-ek-10gd6x-90yv0f60-m0nm00',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3080-rog-strix-oc-10gd6x-90yv0fa1-m0nm00',
    },
    {
      brand: 'asus',
      model: 'strix oc white',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3080-rog-strix-oc-white-10gd6x-90yv0fa5-m0nm00',
    },
    {
      brand: 'asus',
      model: 'strix white',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3080-rog-strix-white-10gd6x-90yv0fa6-m0nm00',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3080-tuf-gaming-10gd6x-90yv0fb0-m0nm00',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3080-tuf-gaming-oc-10gd6x-90yv0fb1-m0nm00',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3080-aorus-master-10gb-gd6x-gvn3080aorusm',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3080-aorus-master-oc-10gb-gd6x-gvn3080am-00-10',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3080-aorus-xtreme-10gb-gd6x-gvn3080ax-00-10',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3080-eagle-10gb-gd6x-gv-n3080eagle-10gd',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3080-eagle-oc-10gb-gd6x-gvn3080eagleoc10gd',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3080-gaming-oc-10gb-gd6x-gvn3080gamingoc10g',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3080-vision-oc-10gb-gd6x-gvn3080visoc-10',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3080-gaming-x-trio-10g-4719072762544',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3080-suprim-x-10g-4719072762537',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3080-ventus-3x-10g-oc-4719072762520',
    },
    {
      brand: 'zotac',
      model: 'amp extreme holo',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3080-amp-extreme-holo-10gb-gd6x-zt-a30800b-10p',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3080-amp-holo-10gb-gd6x-zt-a30800f-10p',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3080-trinity-10gb-gd6x-zt-a30800d-10p',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3080-trinity-oc-10gb-gd6x-zt-a30800j-10p',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-dual-8gb-gd6-90yv0fq1-m0na00',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-dual-oc-8gb-gd6-90yv0fq0-m0na00',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-ek-8gb-gd6-90yv0fu0-m0na00',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-rog-strix-8gb-gd6-90yv0fr0-m0na00',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-rog-strix-oc-8gb-gd6-90yv0fr1-m0na00',
    },
    {
      brand: 'asus',
      model: 'strix oc white',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-rog-strix-oc-white-8gb-gd6-90yv0fr5-m0na00',
    },
    {
      brand: 'asus',
      model: 'strix white',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-rog-strix-white-8gb-gd6-90yv0fr6-m0na00',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-tuf-gaming-8gb-gd6-90yv0fq7-m0na00',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3070-tuf-gaming-oc-8gb-gd6-90yv0fq6-m0na00',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3070-aorus-master-8gb-gd6-gvn3070am-00-11',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3070-eagle-8gb-gd6-gvn3070e-00-10',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3070-eagle-oc-8gb-gd6-gvn3070eo-00-10',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3070-gaming-oc-8gb-gd6-gv-n3070gam-oc-8g',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3070-vision-oc-8gb-gd6-gvn3070vo-00-10',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3070-gaming-x-trio-8g-912-v390-006',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3070-suprim-x-8g-4719072763046',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3070-ventus-2x-oc-8g-912-v390-008',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3070-ventus-3x-oc-8g-912-v390-007',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3070-amp-holo-8gb-gd6-zt-a30700f-10p',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3070-twin-edge-8gb-gd6-zt-a30700e-10p',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3070-twin-edge-oc-8gb-gd6-zt-a30700h-10p',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc white',
      series: '3070',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3070-twin-edge-white-oc-8gb-gd6-zt-a30700j-10p',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3060-ti-aorus-master-8gb-gd6-gvn306tam-00-10',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3060-ti-eagle-8gb-gd6-gvn306te-00-10',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3060-ti-eagle-oc-8gb-gd6-gvn306teo-00-10',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3060-ti-gaming-oc-8gb-gd6-gvn306tgo-00-10',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc pro',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3060-ti-gaming-oc-pro-8gb-gd6-gvn306tgop-00-10',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-ti-ventus-3x-oc-8g-4719072763152',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-ti-gaming-x-trio-8g-912-v390-053',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-ti-rog-strix-8gb-gd6-90yv0g00-m0na00',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-ti-dual-8gb-gd6-90yv0g13-m0na00',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-ti-dual-oc-8gb-gd6-90yv0g12-m0na00',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-ti-tuf-gaming-8gb-gd6-90yv0g11-m0na00',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-ti-tuf-gaming-oc-8gb-gd6-90yv0g10-m0na00',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-ti-rog-strix-oc-8gb-gd6-90yv0g02-m0na00',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3060-ti-twin-edge-8gb-gd6-zt-a30610e-10m',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3060-ti-twin-edge-oc-8gb-gd6-zt-a30610h-10m',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-ti-ventus-2x-ocv1-8g-912-v397-003',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3060-ti-vision-oc-8gb-gd6-gv-n306tvisoc-8gd',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-rog-strix-12gb-gd6-90yv0gc4-m0na00',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-rog-strix-oc-12gb-gd6-90yv0gc2-m0na00',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-tuf-gaming-12gb-gd6-90yv0gc1-m0na00',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-tuf-gaming-oc-12gb-gd6-90yv0gc0-m0na00',
    },
    {
      brand: 'asus',
      model: 'dual mini oc',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-asus-geforce-rtx-3060-ti-dual-mini-oc-8gb-gd6-90yv0ft0-m0na00',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060ti',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-ti-gaming-x-8g-4719072781767',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3060-twin-edge-12gb-gd6-zt-a30600e-10m',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3060-amp-edition-white-12gb-gd6-zt-a30600f-10p',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-zotac-geforce-rtx-3060-twin-edge-oc-12gb-gd6-zt-a30600h-10m',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-gaming-x-trio-12g-912-v390-081',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-gaming-x-12g-912-v397-037',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-ventus-2x-12g-oc-912-v397-039',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-gigabyte-geforce-rtx-3060-gaming-oc-12gb-gd6-gvn3060go-00-10',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-ventus-3x-12g-oc-912-v397-038',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060',
      url: 'https://www.globaldata.pt/grafica-msi-geforce-rtx-3060-ventus-2x-12g-4719072803407',
    },
    {
      brand: 'amd',
      model: '5600x',
      series: 'ryzen5600',
      url: 'https://www.globaldata.pt/processador-amd-ryzen-5-5600x-6-core-37ghz-46ghz-35mb-am4-100-100000065box',
    },
    {
      brand: 'amd',
      model: '5800x',
      series: 'ryzen5800',
      url: 'https://www.globaldata.pt/processador-amd-ryzen-7-5800x-8-core-38ghz-47ghz-36mb-am4-100-100000063wof',
    },
    {
      brand: 'amd',
      model: '5900x',
      series: 'ryzen5900',
      url: 'https://www.globaldata.pt/processador-amd-ryzen-9-5900x-12-core-37ghz-48ghz-70mb-am4-100-100000061wof',
    },
    {
      brand: 'amd',
      model: '5950x',
      series: 'ryzen5950',
      url: 'https://www.globaldata.pt/processador-amd-ryzen-9-5950x-16-core-34ghz-49ghz-72mb-am4-100-100000059wof',
    },
  ],
  name: 'globaldata',
  country: 'PT',
  waitUntil: 'domcontentloaded',
};
