import {Store} from './store';

export const KomplettNO: Store = {
  currency: 'kr.',
  labels: {
    inStock: {
      container:
        '.product-main-info-buy-button > div:nth-child(1) > button:nth-child(1)',
      text: ['LEGG I HANDLEKURV'],
    },
    outOfStock: {
      container:
        '#MainContent > div.no-bs-center.maincontent-container.container.main-body.ignore-gutter-xs.product-page-boxes > div.responsive-content-wrapper > div.product-page > section > div > section > div.product-main-info__body > div.product-main-info__buy-and-more > div.buy-button-section > div > div > div.subscribe-product-container > div > div > button',
      text: ['MOTTA VARSEL'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.komplett.no/product/1307896/pc-nettbrett/nettbrett-ipad-lesebrett/nettbrett-ipad/xiaomi-redmi-pad-se-128gb-graphite-gray',
    },
    {
      brand: 'gainward',
      model: 'phantom',
      series: '5090',
      url: 'https://www.komplett.no/product/1318990/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-5090-phantom',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '5090',
      url: 'https://www.komplett.no/product/1319436/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-5090-gaming-oc',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '5090',
      url: 'https://www.komplett.no/product/1319418/datautstyr/pc-komponenter/skjermkort/gigabyte-aorus-geforce-rtx-5090-master',
    },
    {
      brand: 'gigabyte',
      model: 'windforce oc',
      series: '5090',
      url: 'https://www.komplett.no/product/1319443/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-5090-windforce-oc',
    },
    {
      brand: 'gigabyte',
      model: 'master ice',
      series: '5090',
      url: 'https://www.komplett.no/product/1319444/datautstyr/pc-komponenter/skjermkort/gigabyte-aorus-geforce-rtx-5090-master-ice',
    },    
    {
      brand: 'msi',
      model: 'gaming trio oc',
      series: '5090',
      url: 'https://www.komplett.no/product/1319408/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5090-gaming-trio-oc',
    },        
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '5090',
      url: 'https://www.komplett.no/product/1319421/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5090-ventus-3x-oc',
    },      
    {
      brand: 'msi',
      model: 'suprim soc',
      series: '5090',
      url: 'https://www.komplett.no/product/1319422/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5090-suprim-soc',
    },    
    {
      brand: 'asus',
      model: 'astral',
      series: '5090',
      url: 'https://www.komplett.no/product/1319468/datautstyr/pc-komponenter/skjermkort/asus-rog-astral-geforce-rtx-5090',
    },   
    {
      brand: 'asus',
      model: 'tuf gaming oc',
      series: '5090',
      url: 'https://www.komplett.no/product/1319469/datautstyr/pc-komponenter/skjermkort/asus-tuf-gaming-geforce-rtx-5090-oc',
    },   
    {
      brand: 'gigabyte',
      model: 'windforce',
      series: '5080',
      url: 'https://www.komplett.no/product/1318911/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-5080-windforce-ssf',
    },   
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '5080',
      url: 'https://www.komplett.no/product/1318904/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-5080-phoenix',
    },   
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '5080',
      url: 'https://www.komplett.no/product/1318985/datautstyr/pc-komponenter/skjermkort/palit-geforce-rtx-5080-gamerock-oc',
    },   
    {
      brand: 'palit',
      model: 'gamerock',
      series: '5080',
      url: 'https://www.komplett.no/product/1318987/datautstyr/pc-komponenter/skjermkort/palit-geforce-rtx-5080-gamerock',
    },   
    {
      brand: 'palit',
      model: 'gaming pro oc',
      series: '5080',
      url: 'https://www.komplett.no/product/1318986/datautstyr/pc-komponenter/skjermkort/palit-geforce-rtx-5080-gamingpro-oc',
    },   
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '5080',
      url: 'https://www.komplett.no/product/1318984/datautstyr/pc-komponenter/skjermkort/palit-geforce-rtx-5080-gamingpro',
    },   
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '5080',
      url: 'https://www.komplett.no/product/1318908/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-5080-phantom-gs',
    },   
    {
      brand: 'msi',
      model: 'gaming trio oc',
      series: '5080',
      url: 'https://www.komplett.no/product/1319045/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-gaming-trio-oc',
    },   
    {
      brand: 'msi',
      model: 'gaming trio oc white',
      series: '5080',
      url: 'https://www.komplett.no/product/1319070/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-gaming-trio-oc-hvit',
    },   
    {
      brand: 'msi',
      model: 'ventus 3x oc plus',
      series: '5080',
      url: 'https://www.komplett.no/product/1319044/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-ventus-3x-oc-plus',
    },   
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '5080',
      url: 'https://www.komplett.no/product/1318909/datautstyr/pc-komponenter/skjermkort/gainward-geforce-rtx-5080-phoenix-gs',
    },   
    {
      brand: 'gigabyte',
      model: 'aero oc',
      series: '5080',
      url: 'https://www.komplett.no/product/1318913/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-5080-aero-oc',
    },   
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '5080',
      url: 'https://www.komplett.no/product/1318910/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-5080-gaming-oc',
    },   
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '5080',
      url: 'https://www.komplett.no/product/1318906/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-5080-aorus-master',
    },   
    {
      brand: 'msi',
      model: 'suprim soc',
      series: '5080',
      url: 'https://www.komplett.no/product/1319047/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-suprim-soc',
    },   
    {
      brand: 'gigabyte',
      model: 'master ice',
      series: '5080',
      url: 'https://www.komplett.no/product/1319430/datautstyr/pc-komponenter/skjermkort/gigabyte-aorus-geforce-rtx-5080-master-ice',
    },   
    {
      brand: 'zotac',
      model: 'solid oc',
      series: '5080',
      url: 'https://www.komplett.no/product/1319406/datautstyr/pc-komponenter/skjermkort/zotac-gaming-geforce-rtx-5080-solid-oc',
    },   
    {
      brand: 'zotac',
      model: 'amp extreme infinity',
      series: '5080',
      url: 'https://www.komplett.no/product/1319407/datautstyr/pc-komponenter/skjermkort/zotac-gaming-geforce-rtx-5080-amp-extreme-infinity',
    },   
    {
      brand: 'zotac',
      model: 'solid',
      series: '5080',
      url: 'https://www.komplett.no/product/1319423/datautstyr/pc-komponenter/skjermkort/zotac-gaming-geforce-rtx-5080-solid',
    },   
    {
      brand: 'pny',
      model: 'gaming',
      series: '5080',
      url: 'https://www.komplett.no/product/1319103/datautstyr/pc-komponenter/skjermkort/pny-geforce-rtx-5080-argb-oc',
    },   
    {
      brand: 'pny',
      model: 'gaming',
      series: '5080',
      url: 'https://www.komplett.no/product/1319104/datautstyr/pc-komponenter/skjermkort/pny-geforce-rtx-5080-oc',
    },   
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '5080',
      url: 'https://www.komplett.no/product/1319480/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-ventus-3x-oc',
    },   
    {
      brand: 'asus',
      model: 'tuf',
      series: '5080',
      url: 'https://www.komplett.no/product/1319346/datautstyr/pc-komponenter/skjermkort/asus-tuf-gaming-geforce-rtx-5080',
    },   
    {
      brand: 'asus',
      model: 'astral',
      series: '5080',
      url: 'https://www.komplett.no/product/1319347/datautstyr/pc-komponenter/skjermkort/asus-rog-astral-geforce-rtx-5080',
    },   
    {
      brand: 'gigabyte',
      model: 'windforce oc',
      series: '5080',
      url: 'https://www.komplett.no/product/1319417/datautstyr/pc-komponenter/skjermkort/gigabyte-geforce-rtx-5080-windforce-oc-sff',
    },  
    {
      brand: 'msi',
      model: 'ventus 3x oc white',
      series: '5080',
      url: 'https://www.komplett.no/product/1319049/datautstyr/pc-komponenter/skjermkort/msi-geforce-rtx-5080-ventus-3x-oc-hvit',
    },  
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.komplett.no/product/1168379/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.komplett.no/product/1168439/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.komplett.no/product/1168358/',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.komplett.no/product/1168436/',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.komplett.no/product/1176247/',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.komplett.no/product/1168419',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.komplett.no/product/1171562',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.komplett.no/product/1168418',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.komplett.no/product/1175718',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.komplett.no/product/1168415',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.komplett.no/product/1168416',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3080',
      url: 'https://www.komplett.no/product/1171801',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3080',
      url: 'https://www.komplett.no/product/1171798',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3080',
      url: 'https://www.komplett.no/product/1168422',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3080',
      url: 'https://www.komplett.no/product/1168129',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.komplett.no/product/1168398',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://www.komplett.no/product/1170425',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3080',
      url: 'https://www.komplett.no/product/1168128',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3090',
      url: 'https://www.komplett.no/product/1168378/',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3090',
      url: 'https://www.komplett.no/product/1173670',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3090',
      url: 'https://www.komplett.no/product/1168381/',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3090',
      url: 'https://www.komplett.no/product/1174234',
    },
    {
      brand: 'asus',
      model: 'strix oc white',
      series: '3090',
      url: 'https://www.komplett.no/product/1176245',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3090',
      url: 'https://www.komplett.no/product/1168359',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.komplett.no/product/1168438',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3090',
      url: 'https://www.komplett.no/product/1168490',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3090',
      url: 'https://www.komplett.no/product/1168437',
    },

    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3090',
      url: 'https://www.komplett.no/product/1168414',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3090',
      url: 'https://www.komplett.no/product/1173940',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3090',
      url: 'https://www.komplett.no/product/1168417',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3090',
      url: 'https://www.komplett.no/product/1168412',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3090',
      url: 'https://www.komplett.no/product/1168413',
    },
    {
      brand: 'gigabyte',
      model: 'turbo',
      series: '3090',
      url: 'https://www.komplett.no/product/1171270',
    },
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '3090',
      url: 'https://www.komplett.no/product/1171795',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3090',
      url: 'https://www.komplett.no/product/1171802',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3090',
      url: 'https://www.komplett.no/product/1168127',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060',
      url: 'https://www.komplett.no/product/1178869/',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060',
      url: 'https://www.komplett.no/product/1178866/',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060',
      url: 'https://www.komplett.no/product/1179439/',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3060',
      url: 'https://www.komplett.no/product/1179437/',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060',
      url: 'https://www.komplett.no/product/1179436/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3060',
      url: 'https://www.komplett.no/product/1179440/',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3060',
      url: 'https://www.komplett.no/product/1178552/',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060',
      url: 'https://www.komplett.no/product/1180868/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060',
      url: 'https://www.komplett.no/product/1180869/',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3060',
      url: 'https://www.komplett.no/product/1178553/',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3060',
      url: 'https://www.komplett.no/product/1180406/',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3060',
      url: 'https://www.komplett.no/product/1180407/',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3060',
      url: 'https://www.komplett.no/product/1180411/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060',
      url: 'https://www.komplett.no/product/1178867/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060',
      url: 'https://www.komplett.no/product/1178870/',
    },
    {
      brand: 'palit',
      model: 'dual oc',
      series: '3060',
      url: 'https://www.komplett.no/product/1180408/',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3060',
      url: 'https://www.komplett.no/product/1180413/',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3060',
      url: 'https://www.komplett.no/product/1180412/',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.komplett.no/product/1168752/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3070',
      url: 'https://www.komplett.no/product/1171368/',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3070',
      url: 'https://www.komplett.no/product/1177553/',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc white',
      series: '3070',
      url: 'https://www.komplett.no/product/1175619/',
    },
    {
      brand: 'asus',
      model: 'strix oc white',
      series: '3070',
      url: 'https://www.komplett.no/product/1176244/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3070',
      url: 'https://www.komplett.no/product/1173939/',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1173938/',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3070',
      url: 'https://www.komplett.no/product/1171796/',
    },
    {
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1172252/',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3070',
      url: 'https://www.komplett.no/product/1175239/',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '3070',
      url: 'https://www.komplett.no/product/1176458/',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1171385/',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3070',
      url: 'https://www.komplett.no/product/1176459/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1168375/',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1168376/',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.komplett.no/product/1168399/',
    },
    {
      brand: 'asus',
      model: 'strix white',
      series: '3070',
      url: 'https://www.komplett.no/product/1176246/',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3070',
      url: 'https://www.komplett.no/product/1174190/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1171367/',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3070',
      url: 'https://www.komplett.no/product/1174400/',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1171366/',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3070',
      url: 'https://www.komplett.no/product/1176557/',
    },
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1174399/',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3070',
      url: 'https://www.komplett.no/product/1174397/',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3070',
      url: 'https://www.komplett.no/product/1174396/',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.komplett.no/product/1170422/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.komplett.no/product/1168754/',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174210/',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1178723/',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174392/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174509/',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174206/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174508/',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174275/',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174511/',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174276/',
    },
    {
      brand: 'gainward',
      model: 'ghost oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174403/',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174211/',
    },
    {
      brand: 'palit',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174401/',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1175541/',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1177556/',
    },
    {
      brand: 'msi',
      model: 'ventus 2x',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1176385/',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1177557/',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174395/',
    },
    {
      brand: 'palit',
      model: 'dual oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174394/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174208/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174209/',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc pro',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174510/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174512/',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1174207/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3060ti',
      url: 'https://www.komplett.no/product/1175535/',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070',
      url: 'https://www.komplett.no/product/1168377/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3060',
      url: 'https://www.komplett.no/product/1182236/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3060',
      url: 'https://www.komplett.no/product/1180870/',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060',
      url: 'https://www.komplett.no/product/1179438/',
    },
    {
      brand: 'msi',
      model: 'dual',
      series: '3060',
      url: 'https://www.komplett.no/product/1179340/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.komplett.no/product/1176248/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '3090',
      url: 'https://www.komplett.no/product/1175706/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '3080',
      url: 'https://www.komplett.no/product/1175704/',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3080',
      url: 'https://www.komplett.no/product/1174235/',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3090',
      url: 'https://www.komplett.no/product/1171803/',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3080',
      url: 'https://www.komplett.no/product/1171800/',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3090',
      url: 'https://www.komplett.no/product/1171799/',
    },
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '3080',
      url: 'https://www.komplett.no/product/1171797/',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3090',
      url: 'https://www.komplett.no/product/1168420/',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3090',
      url: 'https://www.komplett.no/product/1168126/',
    },
  ],
  name: 'komplett-no',
  country: 'NO',
};
