import {Store} from './store';

export const MSI: Store = {
  currency: '$',
  labels: {
    inStock: {
      container: '#button-cart',
      text: ['ADD TO CART'],
    },
    outOfStock: {
      container: '#product_qty > button.btn.add-cart-button-3',
      text: ['Notify Me'],
    },
    maxPrice: {
      container: '#prices-new',
    },
  },
  links: [
    {
      brand: 'msi',
      model: 'vanguard soc',
      series: '5090',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5090-32G%20-VANGUARD-SOC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2472',
    },
    {
      brand: 'msi',
      model: 'gaming trio oc',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-GAMING-TRIO-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2480',
    },
    {
      brand: 'msi',
      model: 'gaming trio oc white',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-GAMING-TRIO-OC-WHITE",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2479',
    },
    {
      brand: 'msi',
      model: 'inspire 3x',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-INSPRIE-3X-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2481',
    },
    {
      brand: 'msi',
      model: 'shadow 3x',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-SHADOW-3X-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2485',
    },
    {
      brand: 'msi',
      model: 'suprim liquid soc',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-SUPRIM-LIQUID-SOC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2475',
    },
    {
      brand: 'msi',
      model: 'suprim soc',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-SUPRIM-SOC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2476',
    },
    {
      brand: 'msi',
      model: 'vanguard soc',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-VANGUARD-SOC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2478',
    },
    {
      brand: 'msi',
      model: 'vanguard soc launch edition',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-VANGUARD-SOC-LAUNCH-EDITION",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2477',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-VENTUS-3X",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2487',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-VENTUS-3X-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2482',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc plus',
      series: '5080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5080-16G-VENTUS-3X-OC-PLUS",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2483',
    },
    {
      brand: 'msi',
      model: 'gaming trio oc',
      series: '5090',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-5090-32G-GAMING-TRIO-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2473',
    },
    {
      brand: 'msi',
      model: 'suprim liquid soc',
      series: '5090',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5090-32G-SUPRIM-LIQUID-SOC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2469',
    },
    {
      brand: 'msi',
      model: 'suprim oc',
      series: '5090',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/Geforce-RTX-5090-32G-SUPRIM-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2470',
    },
    {
      brand: 'msi',
      model: 'vanguard soc launch edition',
      series: '5090',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5090-32G-VANGUARD-SOC-LAUNCH-EDITION",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2471',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '5090',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series/GeForce-RTX-5090-32G-VENTUS-3X-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-50-Series?product_id=2474',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '4060',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series/GeForce-RTX-4060-VENTUS-2X-BLACK-8G-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series?product_id=1799',
    },
    {
      brand: 'msi',
      model: 'ventus 2x white oc',
      series: '4060',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series/GeForce-RTX-4060-VENTUS-2X-WHITE-8G-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series?product_id=1852',
    },
    {
      brand: 'msi',
      model: 'gaming x slim',
      series: '4070super',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series/GeForce-RTX-4070-SUPER-12G-GAMING-X-SLIM",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series?product_id=2055',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '4070super',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series/GeForce-RTX-4070-SUPER-12G-VENTUS-2X-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series?product_id=2057',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '4070super',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series/GeForce-RTX-4070-SUPER-12G-VENTUS-3X-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series?product_id=2050',
    },
    {
      brand: 'msi',
      model: 'expert',
      series: '4070ti',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series/GeForce-RTX-4070-Ti-SUPER-16G-EXPERT",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series?product_id=2174',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '4070',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series/GeForce-RTX-4070-VENTUS-3X-12G-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series?product_id=1741',
    },
    {
      brand: 'msi',
      model: 'ventus 3x e1 oc',
      series: '4070',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series/GeForce-RTX-4070-VENTUS-3X-E1-12G-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-40-Series?product_id=2361',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3050',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series/GeForce-RTX-3050-GAMING-X-6G",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series?product_id=2140',
    },
    {
      brand: 'msi',
      model: 'lp oc',
      series: '3050',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series/GeForce-RTX-3050-LP-6G-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series?product_id=2138',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3050',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series/GeForce-RTX-3050-VENTUS-2X-6G-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series?product_id=2139',
    },
    {
      brand: 'msi',
      model: 'gaming trio',
      series: '3080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series/GeForce-RTX-3080-Gaming-Z-Trio-10G-LHR",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series?product_id=954',
    },
    {
      brand: 'msi',
      model: 'gaming trio',
      series: '3080',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series/GeForce-RTX-3080-GAMING-Z-TRIO-12G-LHR",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series?product_id=1246',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080ti',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series/GeForce-RTX-3080-Ti-Gaming-X-Trio-12G",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series?product_id=940',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080ti',
      // "https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series/GeForce-RTX-3080-Ti-Ventus-3X-12G-OC",
      url: 'https://us-store.msi.com/Graphics-Cards/NVIDIA-GPU/GeForce-RTX-30-Series?product_id=939',
    },
  ],
  name: 'msi',
  country: 'US',
};
