import {Store} from './store';

export const PowerNO: Store = {
  currency: 'kr.',
  labels: {
    inStock: {
      container:
        '#product-intro > div.container.old-product-page.ng-star-inserted > div > div > div.col-md-7 > div > div.product-control > div.buy-area.ng-star-inserted > div.buy-area__webshop > button',
      text: ['Legg til handlekurv'],
    },
    outOfStock: {
      container:
        '#product-intro > div.container.old-product-page.ng-star-inserted > div > div > div.col-md-7 > div > div.product-control > div.buy-area.ng-star-inserted > div > button',
      text: ['Ikke på lager'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.power.no/data-og-tilbehoer/p-1128968/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1118420/',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1118419/',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1145753/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1115923/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1117755/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1141929/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1141928/',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1121308/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1121307/',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1118416/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1118415/',
    },
    {
      brand: 'pny',
      model: 'xlr8 epic x',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/p-1128968/',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060ti',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-tuf-gaming-geforce-rtx-3060-ti-oc-edition-grafikkort/p-1132911/',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-geforce-rtx-3090-oc-edition-24-gb-grafikkort/p-1128962/',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-tuf-gaming-rtx-3070-oc-8gb/p-1135069/',
    },
    {
      brand: 'pny',
      model: 'xlr8 uprising',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/pny-geforce-rtx-3070-8-gb-uprising-dual-fan-edition-grafikkort/p-1128969/',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-dual-geforce-rtx-3060-ti-grafikkort/p-1132914/',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/pny-geforce-rtx-3070-8-gb-xlr8-gaming-revel-epic-x-rgb-triple-fan-edition-grafikkort/p-1128970/',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-rtx-3070-oc-8gb/p-1135068/',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-dual-rtx-3060-ti-mini-oc-8-gb-grafikkort/p-1141085/',
    },
    {
      brand: 'pny',
      model: 'xlr8 uprising',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/pny-geforce-rtx-3080-10-gb-xlr8-gaming-uprising-epic-x-rgb-triple-fan-edition-grafikkort/p-1128968/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3080-10-gb-ventus-3x-oc-grafikkort/p-1118420/',
    },
    {
      brand: 'msi',
      model: 'strix',
      series: '3060ti',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-geforce-rtx-3060-ti-grafikkort/p-1132910/',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-dual-geforce-rtx-3070-8-gb-grafikkort/p-1117757/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-tuf-gaming-geforce-rtx-3080-10-gb-grafikkort/p-1115923/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-geforce-rtx-3070-8-gb-grafikkort/p-1117756/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-geforce-rtx-3080-10-gb-grafikkort/p-1117755/',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3090-suprim-x-24g-grafikkort/p-1145754/',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-dual-geforce-rtx-3060-12-gb-grafikkort/p-1167374/',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-dual-geforce-rtx-3060-12-gb-oc-edition-grafikkort/p-1167373/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-tuf-gaming-geforce-rtx-3060-12-gb-grafikkort/p-1167372/',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-tuf-gaming-geforce-rtx-3060-12-gb-oc-edition-grafikkort/p-1167371/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-geforce-rtx-3060-12-gb-grafikkort/p-1167370/',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-geforce-rtx-3060-12-gb-oc-edition-grafikkort/p-1167369/',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3060-gaming-x-trio-12-gb-grafikkort/p-1163157/',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3060-gaming-x-12-gb-grafikkort/p-1163156/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3070-8-gb-ventus-3x-oc-grafikkort/p-1147092/',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3080-suprim-x-10g-grafikkort/p-1145753/',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3070-ventus-2x-oc-grafikkort/p-1145752/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-gf-rtx-3090-aorus-xtreme-24-gb-grafikkort/p-1141935/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-gf-rtx-3090-aorus-master-24-gb-grafikkort/p-1141934/',
    },
    {
      brand: 'gigabyte',
      model: 'turbo',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-geforce-rtx-3090-turbo-24-gb-grafikkort/p-1141933/',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-geforce-rtx-3090-vision-oc-24-gb-grafikkort/p-1141932/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-rtx-3090-aorus-xtreme-wf-24-gb-grafikkort/p-1141931/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-aorus-geforce-rtx-3090-xtreme-waterforce-wb-24-gb-grafikkort/p-1141930/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-gf-rtx-3080-aorus-xtreme-10-gb-grafikkort/p-1141929/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-geforce-rtx-3080-eagle-10-gb-grafikkort/p-1141928/',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-dual-rtx-3060-ti-mini-8-gb-grafikkort/p-1141086/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060ti',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-tuf-gaming-geforce-rtx-3060-ti-grafikkort/p-1132912/',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060ti',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-geforce-rtx-3060-ti-oc-edition-grafikkort/p-1132909/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3070',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-tuf-gaming-geforce-rtx-3070-8-gb-grafikkort/p-1130029/',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/pny-geforce-rtx-3090-24-gb-xlr8-gaming-revel-epic-x-rgb-triple-fan-edition-grafikkort/p-1128967/',
    },
    {
      brand: 'pny',
      model: 'xlr8 uprising',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/pny-geforce-rtx-3090-24-gb-xlr8-gaming-uprising-epic-x-rgb-triple-fan-edition-grafikkort/p-1128966/',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/pny-geforce-rtx-3080-10-gb-xlr8-gaming-revel-epic-x-rgb-triple-fan-edition-grafikkort/p-1128965/',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-geforce-rtx-3080-vision-oc-10-gb-grafikkort/p-1121308/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-aorus-geforce-rtx-3080-master-10-gb-grafikkort/p-1121307/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-aorus-geforce-rtx-3090-master-24-gb-grafikkort/p-1121304/',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-aorus-geforce-rtx-3090-xtreme-24-gb-grafikkort/p-1121303/',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3090-24-gb-ventus-3x-oc-grafikkort/p-1118422/',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/msi-geforce-rtx-3090-24-gb-gaming-x-trio-grafikkort/p-1118421/',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-geforce-rtx-3090-24-gb-gaming-oc-grafikkort/p-1118418/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-geforce-rtx-3090-24-gb-eagle-oc-grafikkort/p-1118417/',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-geforce-rtx-3080-10-gb-gaming-oc-grafikkort/p-1118416/',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/gigabyte-geforce-rtx-3080-10-gb-eagle-oc-grafikkort/p-1118415/',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-rog-strix-geforce-rtx-3090-24-gb-grafikkort/p-1117754/',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3090',
      url: 'https://www.power.no/data-og-tilbehoer/datakomponenter/grafikkort/asus-tuf-gaming-geforce-rtx-3090-24-gb-grafikkort/p-1115922/',
    },
  ],
  name: 'power-no',
  country: 'NO',
};
