import {Store} from './store';

export const ProshopNO: Store = {
  currency: 'kr.',
  labels: {
    inStock: {
      container:
        '.site-product-demorelation-buybtn-container > form:nth-child(1) > button:nth-child(3)',
      text: ['Kjøp'],
    },
    outOfStock: {
      container: '.site-stock',
      text: ['Bestilt'],
    },
  },
  // 
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.proshop.no/Kabinett-tilbehoer/DUTZO-Air-Duster-Vacuum-cleaner-2-in-1-3-speed/3205554',
    },
    {
      brand: 'asus',
      model: 'astral oc',
      series: '5090',
      url: 'https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-5090-ROG-Astral-OC-32GB-GDDR7-RAM-Grafikkort/3331069',
    },
    {
      brand: 'asus',
      model: 'astral',
      series: '5090',
      url: 'https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-5090-ROG-Astral-32GB-GDDR7-RAM-Grafikkort/3331068',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '5090',
      url: 'https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-5090-TUF-32GB-GDDR7-RAM-Grafikkort/3331066',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '5090',
      url: 'https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-5090-OC-32GB-GDDR7-RAM-Grafikkort/3331067',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '5090',
      url: 'https://www.proshop.no/Grafikkort/Inno3D-GeForce-RTX-5090-iCHILL-X3-32GB-GDDR7-RAM-Grafikkort/3332310',
    },
    {
      brand: 'zotac',
      model: 'solid oc',
      series: '5090',
      url: 'https://www.proshop.no/Grafikkort/ZOTAC-GeForce-RTX-5090-Solid-OC-32GB-GDDR7-RAM-Grafikkort/3331164',
    },
    {
      brand: 'msi',
      model: 'vanguard soc',
      series: '5090',
      url: 'https://www.proshop.no/Grafikkort/MSI-GeForce-RTX-5090-Vanguard-SOC-32GB-GDDR7-RAM-Grafikkort/3331269',
    },
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '5090',
      url: 'https://www.proshop.no/Grafikkort/Palit-GeForce-RTX-5090-GameRock-OC-32GB-GDDR7-RAM-Grafikkort/3331211',
    },
    {
      brand: 'asus',
      model: 'prime oc',
      series: '5080',
      url: 'https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-5080-Prime-OC-16GB-GDDR7-RAM-Grafikkort/3326547',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '5080',
      url: 'https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-5080-TUF-16GB-GDDR7-RAM-Grafikkort/3326548',
    },
    {
      brand: 'asus',
      model: 'astral',
      series: '5080',
      url: 'https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-5080-ROG-Astral-16GB-GDDR7-RAM-Grafikkort/3326552',
    },
    {
      brand: 'asus',
      model: 'prime',
      series: '5080',
      url: 'https://www.proshop.no/Grafikkort/ASUS-GeForce-RTX-5080-Prime-16GB-GDDR7-RAM-Grafikkort/3326546',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060ti',
      url: 'https://www.proshop.no/2910054',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2910052',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2911560',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2886986',
    },
    {
      brand: 'inno3d',
      model: 'twin x2',
      series: '3060ti',
      url: 'https://www.proshop.no/2911556',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2886982',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3060ti',
      url: 'https://www.proshop.no/2887734',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3060ti',
      url: 'https://www.proshop.no/2887735',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2887737',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.proshop.no/2886988',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc pro',
      series: '3060ti',
      url: 'https://www.proshop.no/2887738',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2887736',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3060ti',
      url: 'https://www.proshop.no/2908274',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060ti',
      url: 'https://www.proshop.no/2886984',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2908273',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2886990',
    },
    {
      brand: 'asus',
      model: 'dual mini',
      series: '3060ti',
      url: 'https://www.proshop.no/2914081',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060ti',
      url: 'https://www.proshop.no/2886980',
    },
    {
      brand: 'asus',
      model: 'dual mini oc',
      series: '3060ti',
      url: 'https://www.proshop.no/2914082',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3060ti',
      url: 'https://www.proshop.no/2914133',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070',
      url: 'https://www.proshop.no/2876871',
    },
    {
      brand: 'msi',
      model: 'suprim',
      series: '3070',
      url: 'https://www.proshop.no/2908888',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3070',
      url: 'https://www.proshop.no/2876873',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3070',
      url: 'https://www.proshop.no/2876875',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3070',
      url: 'https://www.proshop.no/2885269',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.proshop.no/2876845',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3070',
      url: 'https://www.proshop.no/2876856',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.proshop.no/2878390',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3070',
      url: 'https://www.proshop.no/2878383',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.proshop.no/2878392',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.proshop.no/2878386',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3070',
      url: 'https://www.proshop.no/2876853',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.proshop.no/2876851',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3070',
      url: 'https://www.proshop.no/2876854',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3070',
      url: 'https://www.proshop.no/2883917',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.proshop.no/2876843',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3070',
      url: 'https://www.proshop.no/2878385',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.proshop.no/2911575',
    },
    {
      brand: 'inno3d',
      model: 'twin x2',
      series: '3070',
      url: 'https://www.proshop.no/2883916',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3070',
      url: 'https://www.proshop.no/2883919',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.proshop.no/2911574',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3070',
      url: 'https://www.proshop.no/2911577',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3070',
      url: 'https://www.proshop.no/2883918',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.proshop.no/2911956',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3070',
      url: 'https://www.proshop.no/2912456',
    },
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '3070',
      url: 'https://www.proshop.no/2914382',
    },
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '3070',
      url: 'https://www.proshop.no/2914381',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.proshop.no/2912910',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.proshop.no/2876877',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.proshop.no/2885270',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3080',
      url: 'https://www.proshop.no/2876878',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.proshop.no/2876879',
    },
    {
      brand: 'msi',
      model: 'gaming trio',
      series: '3080',
      url: 'https://www.proshop.no/2876876',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.proshop.no/2876859',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.proshop.no/2876763',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.proshop.no/2876861',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.proshop.no/2911579',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.proshop.no/2876838',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.proshop.no/2878401',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.proshop.no/2876835',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.proshop.no/2876857',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3080',
      url: 'https://www.proshop.no/2887568',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.proshop.no/2878395',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.proshop.no/2876836',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3080',
      url: 'https://www.proshop.no/2878971',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3080',
      url: 'https://www.proshop.no/2878968',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.proshop.no/2911578',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3080',
      url: 'https://www.proshop.no/2878969',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.proshop.no/2876837',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '3080',
      url: 'https://www.proshop.no/2878393',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3080',
      url: 'https://www.proshop.no/2878394',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3090',
      url: 'https://www.proshop.no/2876881',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3090',
      url: 'https://www.proshop.no/2885271',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3090',
      url: 'https://www.proshop.no/2876883',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3090',
      url: 'https://www.proshop.no/2876882',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3090',
      url: 'https://www.proshop.no/2876869',
    },
    {
      brand: 'msi',
      model: 'gaming trio',
      series: '3090',
      url: 'https://www.proshop.no/2876880',
    },
    {
      brand: 'inno3d',
      model: 'gaming x3',
      series: '3090',
      url: 'https://www.proshop.no/2878977',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3090',
      url: 'https://www.proshop.no/2878978',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3090',
      url: 'https://www.proshop.no/2878979',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.proshop.no/2876867',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3090',
      url: 'https://www.proshop.no/2876840',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3090',
      url: 'https://www.proshop.no/2876764',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.proshop.no/2911582',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3090',
      url: 'https://www.proshop.no/2887569',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3090',
      url: 'https://www.proshop.no/2876839',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '3090',
      url: 'https://www.proshop.no/2878404',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3090',
      url: 'https://www.proshop.no/2878413',
    },
    {
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '3090',
      url: 'https://www.proshop.no/2887323',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3090',
      url: 'https://www.proshop.no/2878405',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3090',
      url: 'https://www.proshop.no/2911581',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3090',
      url: 'https://www.proshop.no/2876841',
    },
    {
      brand: 'gigabyte',
      model: 'turbo',
      series: '3090',
      url: 'https://www.proshop.no/2878410',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3090',
      url: 'https://www.proshop.no/2878406',
    },
    {
      brand: 'palit',
      model: 'gamerock oc',
      series: '3090',
      url: 'https://www.proshop.no/2911898',
    },
    {
      brand: 'amd',
      model: '5800x',
      series: 'ryzen5800',
      url: 'https://www.proshop.no/2884171',
    },
    {
      brand: 'amd',
      model: '5900x',
      series: 'ryzen5900',
      url: 'https://www.proshop.no/2884173',
    },
    {
      brand: 'amd',
      model: '5950x',
      series: 'ryzen5950',
      url: 'https://www.proshop.no/2884175',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3060',
      url: 'https://www.proshop.no/2918899',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3060',
      url: 'https://www.proshop.no/2918921',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3060',
      url: 'https://www.proshop.no/2918919',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060',
      url: 'https://www.proshop.no/2918909',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060',
      url: 'https://www.proshop.no/2918930',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060',
      url: 'https://www.proshop.no/2918906',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3060',
      url: 'https://www.proshop.no/2918934',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3060',
      url: 'https://www.proshop.no/2918934',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060',
      url: 'https://www.proshop.no/2918925',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3060',
      url: 'https://www.proshop.no/2918901',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060',
      url: 'https://www.proshop.no/2918904',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060',
      url: 'https://www.proshop.no/2918907',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3060',
      url: 'https://www.proshop.no/2918932',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3060',
      url: 'https://www.proshop.no/2918935',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3060',
      url: 'https://www.proshop.no/2918927',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060',
      url: 'https://www.proshop.no/2918928',
    },
  ],
  name: 'proshop-no',
  country: 'NO',
};
