import {Store} from './store';

export const Scorptec: Store = {
  backoffStatusCodes: [403, 429],
  currency: '$',
  labels: {
    inStock: {
      container: '#delivery-wrapper > div.product-stock-text',
      text: ['in stock'],
    },
    outOfStock: {
      container: '#delivery-wrapper > div.product-stock-text',
      text: ['sold out'],
    },
  },
  links: [
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85443-rog-strix-rtx3080-10g-gaming',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85382-rog-strix-rtx3080-o10g-gaming',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85076-tuf-rtx3080-10g-gaming',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85302-tuf-rtx3080-o10g-gaming',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85194-10g-p5-3895-kr',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85195-10g-p5-3897-kr',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85193-10g-p5-3881-kr',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85269-10g-p5-3883-kr',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85130-10g-p5-3885-kr',
    },
    {
      brand: 'galax',
      model: 'sg oc',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85142-38nwm3md99nn',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85046-gv-n3080gaming-oc-10gd',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85711-gv-n3080aorus-x-10gd',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/86435-gv-n3080aorusx-w-10gd',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/86434-gv-n3080aorusx-wb-10gd',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/86088-gv-n3080eagle-10gd',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85048-gv-n3080eagle-oc-10gd',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85328-gv-n3080aorus-m-10gd',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85329-gv-n3080vision-oc-10gd',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85334-c30804-106xx-1810va36',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85333-c30803-106xx-1810va37',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/86640-geforce-rtx-3080-suprim-x-10g',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85147-geforce-rtx-3080-ventus-3x-10g-oc',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85146-geforce-rtx-3080-gaming-x-trio-10g',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/86188-zt-a30800f-10p',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85038-zt-a30800d-10p',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://www.scorptec.com.au/product/graphics-cards/nvidia/85326-zt-a30800j-10p',
    },
  ],
  name: 'scorptec',
  country: 'AU',
};
