import {Store} from './store';

export const ubiquiti: Store = {
  currency: '$',
  labels: {
    inStock: {
      container: '#addToCart',
      text: ['Add to Cart'],
    },
    maxPrice: {
      container:
        '#bundleApp > div.bundleLogic.add16bottom.add16top > div.one-whole.flex.flex-wrap > div > div.comProduct__price.add16right',
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://store.ui.com/collections/unifi-network-unifi-os-consoles/',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/udm-pro',
      model: 'udm pro',
      series: 'dreammachienepro',
      url: 'https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/udm-pro',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/dream-machine-se',
      model:'udm pro special edition',
      series:'dreammachienepro',
      url:'https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/dream-machine-se',
    },
   /** 
    {
      brand:'ubiquiti',
      cartUrl:'',
      model:'',
      series:'',
      url:'',
    },
    */
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/unifi-dream-machine',
      model:'udm',
      series:'dreammachienepro',
      url:'https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/unifi-dream-machine',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-24-poe',
      model:'pro 24 POE',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-24-poe',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-24',
      model:'pro 24',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-24',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-48-poe',
      model:'48 POE pro',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-48-poe',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-24-poe',
      model:'24 POE',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-24-poe',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-aggregation-pro',
      model:'switch pro aggregation',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-aggregation-pro',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-flex',
      model:'switch flex',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-flex',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-flex',
      model:'flex xg',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-flex',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-flex-mini',
      model:'flex mini',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-flex-mini',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usp-rps',
      model:'redundant power system',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usp-rps',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-48-poe',
      model:'48 POE',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-48-poe',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-48',
      model:'pro 48',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-48',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-lite-16-poe',
      model:'lite 16 POE',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-lite-16-poe',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-lite-8-poe',
      model:'lite 8 POE',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-lite-8-poe',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-aggregation',
      model:'switch aggregation',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-aggregation',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-switching/products/usw-16-poe',
      model:'16 POE',
      series:'switch',
      url:'https://store.ui.com/collections/unifi-network-switching/products/usw-16-poe',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap-6-lite',
      model: 'wifi6 LR',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap-6-lite',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap-6-lite',
      model: 'wifi6 lite',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap-6-lite',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap6-professional',
      model:'wifi6 pro',
      series:'ap',
      url:'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap6-professional',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-wifi-basestation-xg',
      model: 'BaseStation XG',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-wifi-basestation-xg',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-hd',
      model: 'ap HD',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-hd',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-flexhd',
      model: 'ap FLEX HD',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-flexhd',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-in-wall-hd',
      model: 'ap in wall HD',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-in-wall-hd',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-nanohd-us',
      model: 'ap nanoHD',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-nanohd-us',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/uap-beaconhd',
      model: 'ap beaconHD',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/uap-beaconhd',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-building-to-building-bridge',
      model: 'buildtobridgebuild',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-building-to-building-bridge',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-xg-access-point',
      model: 'ap XG',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-xg-access-point',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap-ac-shd',
      model: 'ap SHD',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap-ac-shd',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ac-mesh-ap',
      model: 'ap mesh',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ac-mesh-ap',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ac-lr',
      model: 'ap lr',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ac-lr',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/inwall-ap',
      model: 'ap inwall',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/inwall-ap',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ac-mesh-pro-ap',
      model: 'ap mesh pro',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ac-mesh-pro-ap',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap-6-lite',
      model: 'ap lite',
      series: 'ap',
      url: 'https://store.ui.com/collections/unifi-network-wireless/products/unifi-ap-6-lite',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-24-poe',
      model: 'pro 24 POE',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/usw-pro-24-poe',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/usw-24-poe',
      model: '24 POE',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/usw-24-poe',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/usw-48-poe',
      model: '48 POE',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/usw-48-poe',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/usw-lite-16-poe',
      model: 'lite 16 POE',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/usw-lite-16-poe',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-lite-8-poe',
      model: 'lite 8 POE',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-lite-8-poe',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/usw-16-poe',
      model: '16 POE',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/usw-16-poe',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-8-60w',
      model: '8 (60w)',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-8-60w',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-16-150w',
      model: 'POE 16(150w)',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-16-150w',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-8-150w',
      model: 'POE 8(150w)',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/unifi-switch-8-150w',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/unifiswitch-48-500w',
      model: 'POE+ 48(500w)',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/unifiswitch-48-500w',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-network-switching/products/unifiswitch-24-250w',
      model: 'POE+ 24(250w)',
      series: 'switch',
      url: 'https://store.ui.com/collections/unifi-network-switching/products/unifiswitch-24-250w',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g4-pro-camera',
      model: 'G4 PRO',
      series: 'camera',
      url: 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g4-pro-camera',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g4-ptz',
      model:'g4 ptz',
      series:'camera',
      url:'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g4-ptz',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-protect/products/camera-g4-instant',
      model:'g4 instant',
      series:'camera',
      url:'https://store.ui.com/collections/unifi-protect/products/camera-g4-instant',
    },    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-protect/products/unifi-protect-ai-360',
      model:'ai 360',
      series:'camera',
      url:'https://store.ui.com/collections/unifi-protect/products/unifi-protect-ai-360',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-protect/products/unifi-video-g3-pro-camera-1',
      model:'g3 pro',
      series:'camera',
      url:'https://store.ui.com/collections/unifi-protect/products/unifi-video-g3-pro-camera-1',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-protect/products/uvc-g4-doorbell',
      model:'doorbell g4',
      series:'camera',
      url:'https://store.ui.com/collections/unifi-protect/products/uvc-g4-doorbell',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-protect/products/unifi-video-camera-g3-bullet',
      model: 'G3 Bullet',
      series: 'camera',
      url: 'https://store.ui.com/collections/unifi-protect/products/unifi-video-camera-g3-bullet',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-protect/products/unifi-video-g3-flex-camera',
      model: 'G3 Flex',
      series: 'camera',
      url: 'https://store.ui.com/collections/unifi-protect/products/unifi-video-g3-flex-camera',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g4-dome-camera',
      model: 'G4 Dome',
      series: 'camera',
      url: 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g4-dome-camera',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g3-instant-camera',
      model: 'G3 Instant',
      series: 'camera',
      url: 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g3-instant-camera',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g4-bullet-camera',
      model:'g4 bullet',
      series:'camera',
      url:'https://store.ui.com/collections/unifi-protect/products/unifi-protect-g4-bullet-camera',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-network-video-recorder-pro',
      model: 'video recorder pro',
      series: 'network',
      url: 'https://store.ui.com/collections/unifi-protect/products/unifi-protect-network-video-recorder-pro',
    },
    {
      brand: 'ubiquiti',
      cartUrl: 'https://store.ui.com/collections/unifi-accessories/products/unifi-cloudkey',
      model: 'Gen2',
      series: 'Cloud Key',
      url: 'https://store.ui.com/collections/unifi-accessories/products/unifi-cloudkey',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/unifi-cloudkey-plus',
      model:'gen2+',
      series:'Cloud Key',
      url:'https://store.ui.com/collections/unifi-network-unifi-os-consoles/products/unifi-cloudkey-plus',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-protect-nvr/products/unifi-protect-network-video-recorder-pro',
      model:'nvr pro',
      series:'accessory',
      url:'https://store.ui.com/collections/unifi-protect-nvr/products/unifi-protect-network-video-recorder-pro',
    },
    {
      brand:'ubiquiti',
      cartUrl:'https://store.ui.com/collections/unifi-protect-nvr/products/unifi-protect-nvr',
      model:'nvr',
      series:'accessory',
      url:'https://store.ui.com/collections/unifi-protect-nvr/products/unifi-protect-nvr',
    },
  ],
  name: 'ubiquiti',
};
