import {Store} from './store';

export const Vuugo: Store = {
  currency: '$',
  labels: {
    inStock: {
      container: '.green',
      text: ['In Stock'],
    },
    maxPrice: {
      container: 'div.price:nth-child(12)',
    },
    outOfStock: {
      container: '.description .red',
      text: ['Back Order'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/hard-drives/seagate-hard-drive-ST1000LM048.html',
    },
    {
      brand: 'amd',
      model: '5600x',
      series: 'ryzen5600',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/cpu/amd-cpu-100-100000065BOX.html',
    },
    {
      brand: 'amd',
      model: '5800x',
      series: 'ryzen5800',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/cpu/amd-cpu-100-100000063WOF.html',
    },
    {
      brand: 'amd',
      model: '5900x',
      series: 'ryzen5900',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/cpu/amd-cpu-100-100000061WOF.html',
    },
    {
      brand: 'amd',
      model: '5950x',
      series: 'ryzen5950',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/cpu/amd-cpu-100-100000059WOF.html',
    },
    {
      brand: 'asrock',
      model: 'amd reference',
      series: 'rx6900xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asrock-video-cards-RX6900XT-16G.html',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-DUAL-RTX3060TI-O8G.html',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-DUAL-RTX3070-8G.html',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-DUAL-RTX3070-O8G.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-RTX3060TI-O8G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'ko',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-KO-RTX3070-O8G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-RTX3070-O8G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-RTX3070-O8G-WH.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-RTX3080-O10G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-RTX3080-O10G-WH.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-RTX3090-O24G-GA.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-RTX3090-O24G-WH.html',
    },
    {
      brand: 'asus',
      model: 'strix lc',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-LC-RX6800XT-O16G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: 'rx6800',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-ROG-STRIX-RX6800-O16G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RTX3060TI-O8G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RTX3070-O8G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RTX3080-10G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RTX3080-O10G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RTX3090-O24G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RTX3090-24G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-RTX3090-24G-EK.html',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-RTX3080-10G-EK.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: 'rx6800',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RX6800-O16G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RX6800XT-O16G-GAMING.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: 'rx6900xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/asus-video-cards-TUF-RX6900XT-O16G-GAMING.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-08G-P5-3667-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc gaming',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-08G-P5-3663-KR.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-08G-P5-3765-KR.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-08G-P5-3767-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-08G-P5-3751-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-08G-P5-3753-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-08G-P5-3755-KR.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-10G-P5-3895-KR.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-10G-P5-3897-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-10G-P5-3881-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-10G-P5-3883-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-10G-P5-3885-KR.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-24G-P5-3985-KR.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-24G-P5-3987-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-24G-P5-3973-KR.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/evga-video-cards-24G-P5-3975-KR.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N306TAORUS-M-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3070AORUS%20M-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3080AORUS-M-10GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3090AORUS-M-24GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3080AORUS-X-10GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3090AORUS-X-24GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N306TEAGLE-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N306TEAGLE-OC-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N306TGAMING-OC-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc pro',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N306TGAMINGOC-PRO-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3070EAGLE-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3070EAGLE-OC-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3070GAMING-OC-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3080EAGLE-10GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3080EAGLE-OC-10GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3080GAMING-OC-10GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3080VISION-OC-10GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3090EAGLE-24GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3090EAGLE-OC-24GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3090GAMING-OC-24GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3090VISION-OC-24GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-N3070VISION-OC-8GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: 'rx6800',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-R68GAMING-OC-16GD.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/gigabyte-video-cards-GV-R68XTGAMING-OC-16GD.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G306TGXT.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G306TV2XC.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G3070GXT.html',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G3070SX8.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G3070V2XC.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G3070V3XC.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G3080GXT10.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G3080V3X10C.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G3090GXT24.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-G3090V3X24C.html',
    },
    {
      brand: 'msi',
      model: 'amd reference',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-R6800GXT16.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/msi-video-cards-R6800XTGXT16.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3060ti',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/pny-video-cards-VCG3060T8DFXPPB.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/pny-video-cards-VCG30708TFXPPB.html',
    },
    {
      brand: 'pny',
      model: 'dual fan',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/pny-video-cards-VCG30708DFMPB.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/pny-video-cards-VCG309024TFXPPB.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 uprising',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/pny-video-cards-VCG308010TFXMPB.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 epic x',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/pny-video-cards-VCG308010TFXPPB.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 epic x',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/pny-video-cards-VCG309024TFXMPB.html',
    },
    {
      brand: 'sapphire',
      model: 'nitro+',
      series: 'rx6800',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/sapphire-video-cards-11305-01-20G.html',
    },
    {
      brand: 'sapphire',
      model: 'nitro+',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/sapphire-video-cards-11304-02-20G.html',
    },
    {
      brand: 'sapphire',
      model: 'nitro+ se',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/sapphire-video-cards-11304-01-20G.html',
    },
    {
      brand: 'sapphire',
      model: 'pulse',
      series: 'rx6800',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/sapphire-video-cards-11305-02-20G.html',
    },
    {
      brand: 'sapphire',
      model: 'pulse',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/sapphire-video-cards-11304-03-20G.html',
    },
    {
      brand: 'sapphire',
      model: 'amd reference',
      series: 'rx6800',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/sapphire-video-cards-21305-01-20G.html',
    },
    {
      brand: 'sapphire',
      model: 'amd reference',
      series: 'rx6800xt',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/sapphire-video-cards-21304-01-20G.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/zotac-video-cards-ZT-A30700H-10P.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/zotac-video-cards-ZT-A30700E-10P.html',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/zotac-video-cards-ZT-A30800J-10P.html',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/zotac-video-cards-ZT-A30800D-10P.html',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3090',
      url: 'https://www.vuugo.com/computer-hardware/computer-parts/video-cards/zotac-video-cards-ZT-A30900D-10P.html',
    },
  ],
  name: 'vuugo',
  country: 'CA',
};
