import {Store} from './store';

export const Wipoid: Store = {
  currency: '$',
  labels: {
    inStock: {
      container: '#add_to_cart',
      text: ['COMPRAR'],
    },
    maxPrice: {
      container: '#our_price_display',
      euroFormat: true,
    },
    outOfStock: {
      container: '.buttons_bottom_block no-print',
      text: ['Avísame cuando esté disponible!'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.wipoid.com/pny-geforce-rtx-1650-dual-fan-4gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3060-12gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3060-oc-edition-12gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3060ti',
      url: 'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3060-ti-8gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3060ti',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3060-ti-oc-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3060ti',
      url: 'https://www.wipoid.com/gigabyte-aorus-geforce-rtx-3060-ti-master-8gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3060ti',
      url: 'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3060-ti-oc-edition-8gb-gddr6.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3060ti',
      url: 'https://www.wipoid.com/msi-geforce-rtx-3060-ti-gaming-x-trio-8gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3060ti',
      url: 'https://www.wipoid.com/asus-dual-geforce-rtx-3060-ti-oc-edition-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060ti',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3060-ti-gaming-oc-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc pro',
      series: '3060ti',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3060-ti-gaming-pro-oc-8gb-gddr6.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3060ti',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-ti-twin-edge-oc-8gb-gddr6.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3060ti',
      url: 'https://www.wipoid.com/palit-geforce-rtx-3060-ti-gaming-pro-8gb-gddr6.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3060ti',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3060-ti-twin-edge-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle',
      series: '3060ti',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3060-ti-eagle-8gb-gddr6.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3060ti',
      url: 'https://www.wipoid.com/msi-geforce-rtx-3060-ti-ventus-2x-oc-8gb-gddr6.html',
    },
    {
      brand: 'palit',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.wipoid.com/palit-geforce-rtx-3060-ti-dual-8gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3070',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3070-oc-8gb-gddr6.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3070',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3070-ftw3-ultra-gaming-8gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3070',
      url: 'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3070-oc-edition-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3070',
      url: 'https://www.wipoid.com/gigabyte-aorus-geforce-rtx-3070-master-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3070-vision-oc-8gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3070',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3070-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3070',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3070-gaming-oc-8gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'dual oc',
      series: '3070',
      url: 'https://www.wipoid.com/asus-dual-geforce-rtx-3070-oc-edition-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3070',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3070-eagle-oc-8gb-gddr6.html',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3070',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-amp-holo-8gb-gddr6.html',
    },
    {
      brand: 'asus',
      model: 'dual',
      series: '3070',
      url: 'https://www.wipoid.com/asus-dual-geforce-rtx-3070-8gb-gddr6.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-white-gddr6.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 epic x',
      series: '3070',
      url: 'https://www.wipoid.com/pny-geforce-rtx-3070-xlr8-gaming-epic-x-8gb-gddr6x.html',
    },
    {
      brand: 'pny',
      model: 'dual fan',
      series: '3070',
      url: 'https://www.wipoid.com/pny-geforce-rtx-3070-dual-fan-8gb-gddr6.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-twin-edge-oc-8gb-gddr6.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3070-twin-edge-8gb-gddr6.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3070',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3080-eagle-oc-10gb-gddr6x.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x oc',
      series: '3080',
      url: 'https://www.wipoid.com/msi-geforce-rtx-3080-ventus-3x-10gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3080-10gb-gddr6x.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3080-gaming-oc-10gb-gddr6x.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.wipoid.com/msi-geforce-rtx-3080-gaming-x-trio-10gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3080',
      url: 'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3080-oc-edition-10gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3080',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3080-oc-edition-10gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3080-xc3-black-gaming-10gb-gddr6x.html',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3080-trinity-10gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3080-xc3-ultra-gaming-10gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3080-10gb-gddr6x.html',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3080-trinity-oc-10gb-gddr6x.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3080-vision-oc-10gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3080-xc3-black-gaming-10gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3080-ftw3-ultra-gaming-10gb-gddr6x.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3080',
      url: 'https://www.wipoid.com/gigabyte-aorus-geforce-rtx-3080-master-10gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3080-ftw3-ultra-gaming-10gb-gddr6x.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.wipoid.com/pny-geforce-rtx-3080-10gb-xlr8-gaming-epic-x-rgb-10gb-gddr6x.html',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.wipoid.com/pny-geforce-rtx-3080-10gb-xlr8-gaming-epic-x-rgb-10gb-gddr6x.html',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.wipoid.com/msi-geforce-rtx-3080-suprim-x-10gb-gddr6x.html',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3080-amp-holo-10gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3080-ftw3-gaming-10gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3080-xc3-gaming-10gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3090',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3090-ftw3-ultra-gaming-24gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'ekwb',
      series: '3090',
      url: 'https://www.wipoid.com/asus-ekwb-geforce-rtx-3090-24gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'strix white',
      series: '3090',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3090-oc-edition-white-24gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'tuf oc',
      series: '3090',
      url: 'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3090-oc-edition-24gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3090-oc-edition-24gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3090',
      url: 'https://www.wipoid.com/asus-rog-strix-geforce-rtx-3090-24gb-gddr6x.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3090',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3090-oc-24gb-gddr6x.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3090',
      url: 'https://www.wipoid.com/msi-geforce-rtx-3090-gaming-x-trio-24gb-gddr6x.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3090',
      url: 'https://www.wipoid.com/gigabyte-geforce-rtx-3090-eagle-oc-24gb-gddr6x.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3090',
      url: 'https://www.wipoid.com/asus-tuf-gaming-geforce-rtx-3090-24gb-gddr6x.html',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3090',
      url: 'https://www.wipoid.com/zotac-gaming-geforce-rtx-3090-trinity-24gb-gddr6x.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x',
      series: '3090',
      url: 'https://www.wipoid.com/msi-geforce-rtx-3090-ventus-3x-24gb-gddr6x.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3090',
      url: 'https://www.wipoid.com/evga-geforce-rtx-3090-xc3-ultra-gaming-24gb-gddr6x.html',
    },
    {
      brand: 'amd',
      model: '5600x',
      series: 'ryzen5600',
      url: 'https://www.wipoid.com/amd-ryzen-5-5600x-3-7ghz.html',
    },
    {
      brand: 'amd',
      model: '5800x',
      series: 'ryzen5800',
      url: 'https://www.wipoid.com/amd-ryzen-7-5800x-3-8ghz.html',
    },
    {
      brand: 'amd',
      model: '5900x',
      series: 'ryzen5900',
      url: 'https://www.wipoid.com/amd-ryzen-9-5900x-3-7ghz.html',
    },
    {
      brand: 'amd',
      model: '5950x',
      series: 'ryzen5950',
      url: 'https://www.wipoid.com/amd-ryzen-9-5950x-3-4ghz.html',
    },
  ],
  name: 'wipoid',
  country: 'ES',
};
